"""Organizations

Revision ID: 55dcc428fe3b
Revises: 
Create Date: 2021-02-19 14:12:19.207801

"""
from alembic import op
import sqlalchemy as sa
import src.core.fields_sqlalchemy.types



# revision identifiers, used by Alembic.
revision = '55dcc428fe3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('status_organization', sa.Enum(
            'operating', 'is_liquidation', 'liquidated',
            'process_of_bankruptcy', 'process_of_reorganization',
            name='organizationstatus'
        ), nullable=True),
        sa.Column('ogrn', sa.Integer(), nullable=True),
        sa.Column('ogrn_date_from', sa.Date(), nullable=True),
        sa.Column('date_of_register', sa.Date(), nullable=True),
        sa.Column('law_address', sa.JSON(), nullable=True),
        sa.Column('owner_date_from', sa.Date(), nullable=True),
        sa.Column('inn_number', sa.Integer(), nullable=True),
        sa.Column('kpp_number', sa.Integer(), nullable=True),
        sa.Column('authorized_capital', sa.String(length=255), nullable=True),
        sa.Column('primary_occupation', sa.String(length=255), nullable=True),
        sa.Column('primary_occupation_code', sa.Integer(), nullable=True),
        sa.Column('tax_authority', sa.String(length=255), nullable=True),
        sa.Column('tax_authority_date_from', sa.Date(), nullable=True),
        sa.Column('okpo', sa.Integer(), nullable=True),
        sa.Column('okato', sa.Integer(), nullable=True),
        sa.Column('oktmo', sa.Integer(), nullable=True),
        sa.Column('okfs', sa.Integer(), nullable=True),
        sa.Column('okogu', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_external_id'), 'organizations', ['external_id'], unique=True)
    op.create_index(op.f('ix_organizations_status_organization'), 'organizations', ['status_organization'], unique=False)
    op.create_table('owner',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=True),
        sa.Column('first', sa.String(length=255), nullable=True),
        sa.Column('last', sa.String(length=255), nullable=True),
        sa.Column('middle', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_id'), 'owner', ['id'], unique=False)
    op.create_table('requisites',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.String(length=255), nullable=True),
        sa.Column('ogrn', sa.Integer(), nullable=True),
        sa.Column('req_dt', sa.Date(), nullable=True),
        sa.Column('registrar', sa.String(length=255), nullable=True),
        sa.Column('address', sa.JSON(), nullable=True),
        sa.Column('reg_number', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('category', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisites_req_dt'), 'requisites', ['req_dt'], unique=False)
    op.create_index(op.f('ix_requisites_id'), 'requisites', ['id'], unique=False)
    op.create_index(op.f('ix_requisites_type'), 'requisites', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requisites_type'), table_name='requisites')
    op.drop_index(op.f('ix_requisites_id'), table_name='requisites')
    op.drop_index(op.f('ix_requisites_date'), table_name='requisites')
    op.drop_table('requisites')
    op.drop_index(op.f('ix_owner_id'), table_name='owner')
    op.drop_table('owner')
    op.drop_index(op.f('ix_organizations_status_organization'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_external_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
